# Profile para desenvolvimento local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waldorf_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: waldorf_user
    password: waldorf_pass_2024
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

waldorf:
  storage:
    type: local
    local:
      upload-dir: ./uploads

logging:
  level:
    br.edu.waldorf: DEBUG